### PR TITLE
Summing iterator implementation

### LINKED ISSUE #22: Allow usage with summing iterators
It would be useful if you implemented the [Sum trait](https://doc.rust-lang.org/std/iter/trait.Sum.html) in order to use the .sum() on an iterator over a vec of fractions.
At the moment it fails with the following error:

```
the trait bound `fraction::fraction::GenericFraction<u64>: std::iter::Sum` is not satisfied
the trait `std::iter::Sum` is not implemented for `fraction::fraction::GenericFraction<u64>`rustc(E0277)
```

### PR DESCRIPTION
**Pull request by eutampieri**
This issue aims to close #22 and to fix eutampieri/cardgamesbot#3
It implements the `std::iter::Sum` trait on iterators over `Fraction`s and `Decimal`s in order to easily sum large quantities of these.

### CODE REVIEW

**Comment by eutampieri** [comment]
I would like to know @dnsl48 why do I have to .map(|x| x.clone()) and how to implement on the reference.

**Comment by eutampieri** [comment]
Are you OK with cloning each iterated element if it's not owned?

**Comment by dnsl48** [comment]
Hey @eutampieri, thank you for the PR. It looks good!
Would you also like to add implementation for `std::iter::Product`? That feels to be very similar and I suppose that would have almost identical implementation.

> I would like to know @dnsl48 why do I have to .map(|x| x.clone()) and how to implement on the reference.
Are you OK with cloning each iterated element if it's not owned?

That's a trade-off we have to take to allow heap allocated subtypes (e.g. `Fraction<BigUint>`), which cannot implement `Copy`.
I guess as a workaround you could have a type alias on the application level, implementing a Copy trait, which should allow you to do that without manual cloning.

**Comment by dnsl48** [comment]
On the other hand, I'm contemplating now if we could have a map reduce there, rather than cloning every value.

**Comment by eutampieri** [comment]
Ok, I’ll have a look later today. The time zones delta is really slowing down this pr 😆

**Comment by eutampieri** [comment]
I've implemented the product iterators

File: src/decimal/mod.rs [hunk 1]
```diff
@@ -346,6 +347,54 @@ dec_impl!(impl_trait_proxy;
...
+{
+    fn sum<I: Iterator<Item=Self>>(iter: I) -> Self {
+        iter.fold(GenericDecimal::<T, P>::zero(), Add::add)
+    }
+}
+impl<'a, T, P> Sum<&'a GenericDecimal<T, P>> for GenericDecimal<T, P> where
+    T: Clone + GenericInteger + PartialEq,
+    P: Copy + GenericInteger + Into<usize>,
+{
+    fn sum<I: Iterator<Item=&'a Self>>(iter: I) -> Self {
```
Comment (eutampieri) [inline src/decimal/mod.rs:363]: I had to implement it this way because otherwise I'd get a really long compilation error that was way too long to debug.

**Comment by eutampieri** [comment]
Wow, thank you!

**Comment by eutampieri** [comment]
Have you already published to crates.io?

**Comment by dnsl48** [comment]
> Have you already published to crates.io?

Yes, it's up in `0.6.3`

**Comment by eutampieri** [comment]
Ok thanks again
